Vagrant.configure(2) do |config|
  # setup proxy
  # dependency: `vagrant plugin install vagrant-proxyconf`

    if Vagrant.has_plugin?("vagrant-proxyconf")
      config.proxy.http      = "http://PITC-Zscaler-Americas-Alpharetta3PR.proxy.corporate.ge.com:80"
      config.proxy.https     = "http://PITC-Zscaler-Americas-Alpharetta3PR.proxy.corporate.ge.com:80"
      config.proxy.no_proxy  = "localhost,127.0.0.1"
    end
  config.vm.define "acs" do |acs|
    acs.vm.box = "ubuntu/trusty64"
    acs.vm.hostname = "acs"
    acs.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.define "centos" do |centos|
  centos.vm.box = "centos/7"
  centos.vm.hostname = "centos"
  centos.vm.network "private_network", ip: "192.168.33.30"
end
end
