Vagrant.configure(2) do |config|
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

  # setup proxy
  # dependency: `vagrant plugin install vagrant-proxyconf`
  config.vm.define "ubu" do |ubu|
    ubu.vm.box = "ubuntu/trusty64"
    ubu.vm.hostname = "ubu"
    ubu.vm.network "private_network", ip: "10.10.10.15"
    ubu.vm.provision "shell", inline: "sudo apt-get update -y"
    ubu.vm.provision "shell", inline: "sudo apt-get install docker.io -y"
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.hostname = "centos"
    centos.vm.network "private_network", ip: "10.10.10.14"
    centos.vm.provision "shell", inline: "sudo yum update -y"
    centos.vm.provision "shell", inline: "sudo yum install docker -y"
end
end
